blank_issues_enabled: true
contact_links:
  - name: 📖 CAMARA API Design Guidelines
    url: https://github.com/camaraproject/WorkingGroups/blob/main/Commonalities/documentation/API-design-guidelines.md
    about: Please refer to the design guidelines.
